image: node:latest

# Cache modules in between jobs
cache:
  key: $CI_COMMIT_REF_SLUG
  paths:
    - node_modules/

default:
  interruptible: false
  before_script:
    - curl -f https://get.pnpm.io/v6.16.js | node - add --global pnpm@7
    - pnpm config set store-dir .pnpm-store

stages:
  - lint
  - test

lint-code-job:
  stage: lint
  script:
    - pnpm install
    - pnpm lint

test-code-job:
  stage: test
  script:
    - pnpm i
    - pnpm test
