image: node:16

cache:
  key: $CI_COMMIT_REF_SLUG
  paths:
    - node_modules/
    - .eslintcache

default:
  interruptible: false
  before_script:
    - curl -f https://get.pnpm.io/v6.16.js | node - add --global pnpm@7
    - pnpm install --registry=https://registry.npmmirror.com

stages:
  - lint
  - test

test-code-job:
  stage: test
  script:
    - pnpm test

lint-code-job:
  stage: lint
  script:
    # pnpm -r lint will cause Segmentation fault
    # - pnpm run lint
    - cd frontend/ && pnpm lint
    - cd backend/ && pnpm lint
    - cd common/ && pnpm lint
    - cd pan-store/ && pnpm lint
