image: node:16.18
cache:
  key: $CI_COMMIT_REF_SLUG
  paths:
    - node_modules/
    - .eslintcache

stages:
  - install-deps
  - lint

install-deps:
  stage: install-deps
  script:
    - npm i -g pnpm
    - pnpm i

lint:
  stage: lint
  script:
    - pnpm lint
