image: node:latest

# Cache modules in between jobs
cache:
  key: $CI_COMMIT_REF_SLUG
  paths:
    - node_modules/

default:
  interruptible: false
  before_script:
    - npm i -g pnpm && pnpm install

stages:
  - lint
  - test

lint-code-job:
  stage: lint
  script:
    - pnpm lint

test-code-job:
  stage: test
  script:
    - pnpm test
